### PR TITLE
Add Swift Package Manager support!

### PR DESCRIPTION
**Pull request by nidegen**

### CODE REVIEW

**Comment by nidegen** [comment]
@ocollet not interested?

**Comment by roimulia2** [comment]
@ocollet Can you accept the PR, please?

**Comment by Kondamon** [comment]
This is a duplicate of this merge request: https://github.com/unsplash/unsplash-photopicker-ios/pull/40

**Comment by nidegen** [comment]
but #27 was way earlier. so no, #40 is a dup of #27:)

**Comment by Kondamon** [comment]
> but #27 was way earlier. so no, #40 is a dup of #27:)

Yes, your are right! :) The question is how to merge it soon? It's open for more than 1 year now. And the other one got reviewed and there are just 2 lines of code that needs to be deleted.

**Comment by nidegen** [comment]
oh and its even based on my branch:D. ill close this:)

**Pull request closed without merging**
